#Created by riccardo.rotondo@ct.infn.it

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: vm-weekly-snapshot
  labels:
    app: powercli
spec:
  schedule: "0 2 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vm-weekly-snapshot
            image: vmware/powerclicore
            command: ["/usr/bin/pwsh"]
            env:
              - name: SERVER
                valueFrom:
                  secretKeyRef:
                    name: powercli-secret
                    key: server 
            args: ["/root/script/VMSnapshot.ps1", "-server", "$(SERVER)", 
                  "-credfile", "/root/cred/MyCredential.xml",  
                  "-schedule", "weekly"]
            volumeMounts:
            - name: powercli-secret-credential
              mountPath: /root/cred
            - name: powercli-script-snap
              mountPath: /root/script
          volumes:
          - name: powercli-secret-credential
            secret:
              secretName: powercli-secret-credential
          - name: powercli-script-snap
            configMap:
              name: powercli-script-snap
          restartPolicy: OnFailure
